runtime: nodejs20

env_variables:
  NODE_ENV: production

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65

handlers:
  - url: /.*
    script: auto
    secure: always
